apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
  labels:
    app: nana
spec:
  selector:
    matchLabels:
      app: nana
  replicas: 1
  template:
    metadata:
      labels:
        app: nana
    spec:
      containers:
        - name: nana
          image: nanajanashia/argocd-app:1.0
          ports:
          - containerPort: 80